services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=financial'
      - 'POSTGRES_PASSWORD=etosecret'
      - 'POSTGRES_USER=orikus'
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
