spring:
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_CONNECTION_USERNAME}
    password: ${DB_CONNECTION_PASSWORD}

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_SECRET_ID}
