spring:
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://dpg-cni320g21fec73cp249g-a:5432/financial_mlz2
    username: financial_mlz2_user
    password: GCE7dJkLRRHy5vP7tUi5HJrZA6FhxtVQ

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_SECRET_ID}
#      client:
#        registration:
#          google:
#            client-id: 996678195569-709qfbbjp4rcllpht05os661j9haslp4.apps.googleusercontent.com
#            client-secret: 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
